name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive
          lfs: false
      
      - name: Find Visual C++ compilers and make all environment variables global (W)
        shell: cmd
        run: |
          :: See https://github.com/microsoft/vswhere/wiki/Find-VC
          for /f "usebackq delims=*" %%i in (`vswhere -latest -property installationPath`) do (
            call "%%i"\Common7\Tools\vsdevcmd.bat -arch=x64 -host_arch=x64
          )

          :: Loop over all environment variables and make them global.
          for /f "delims== tokens=1,2" %%a in ('set') do (
            echo>>"%GITHUB_ENV%" %%a=%%b
          )

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build with CMake
        run: |
          cmake -G Ninja -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER="cl" -DCMAKE_CXX_COMPILER="cl"
          cmake --build build
          xcopy /Y /I "build\*.dll" "$env:OUT_DIR"
        shell: cmd
        env:
          OUT_DIR: ${{ github.workspace }}/game/csgo/addons/cs2kz-bridge/bin/

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore and build
        run: |
          dotnet restore --locked-mode
          dotnet build --configuration Release --no-restore
        working-directory: ./src/managed/CS2KZEvents
        env:
          CI: true
          CI_OUTPUT_DIR: ${{ github.workspace }}/game/csgo/addons/swiftlys2/plugins/CS2KZEvents/

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: CS2KZEvents-${{ github.run_number }}
          path: ./game
          compression-level: 9
          if-no-files-found: error
          retention-days: 1
